"""
etl_pipeline.py
----------------
Purpose: ETL (Extract - Transform - Load) pipeline that moves data from
         MySQL OLTP database (flipkart_oltp) into PostgreSQL OLAP data
         warehouse (flipkart_dwh) using a Star Schema.

EXTRACT  -> Read raw transactional data from MySQL
TRANSFORM -> Clean data, derive new fields (age_group, date parts,
             actual delivery days), build dimension & fact records
LOAD     -> Insert into PostgreSQL dimension tables first, then fact table
             (fact table needs the surrogate keys generated by dimensions)

This is the core "Python part" of the project — proving real-world ETL
skills: connecting to two different databases, transforming data, and
loading it in the correct dependency order.
"""

import mysql.connector
import psycopg2
from datetime import datetime, date

# ------------------------------------------------------------------
# DB CONFIGS
# ------------------------------------------------------------------
MYSQL_CONFIG = {
    "host": "localhost",
    "user": "root",              # <-- change if you used a different MySQL user
    "password": "12345",   # <-- update this
    "database": "flipkart_oltp",
}

POSTGRES_CONFIG = {
    "host": "localhost",
    "user": "postgres",
    "password": "12345",         # <-- your postgres password
    "dbname": "flipkart_dwh",
    "port": 5432,
}


def get_mysql_conn():
    return mysql.connector.connect(**MYSQL_CONFIG)


def get_postgres_conn():
    return psycopg2.connect(**POSTGRES_CONFIG)


def age_group(dob):
    """Derive age group from date of birth."""
    if dob is None:
        return "Unknown"
    today = date.today()
    age = today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))
    if age <= 25:
        return "18-25"
    elif age <= 35:
        return "26-35"
    elif age <= 45:
        return "36-45"
    else:
        return "46+"


# ------------------------------------------------------------------
# STEP 1: EXTRACT — pull raw data from MySQL
# ------------------------------------------------------------------
def extract(my_cursor):
    print("EXTRACT: Reading data from MySQL (flipkart_oltp) ...")

    my_cursor.execute("SELECT * FROM user_info")
    users = my_cursor.fetchall()

    my_cursor.execute("SELECT * FROM order_info")
    orders = my_cursor.fetchall()

    my_cursor.execute("SELECT * FROM payment_info")
    payments = my_cursor.fetchall()

    my_cursor.execute("SELECT * FROM logistic_info")
    logistics = my_cursor.fetchall()

    my_cursor.execute("SELECT * FROM rating_review")
    reviews = my_cursor.fetchall()

    print(f"  -> users: {len(users)}, orders: {len(orders)}, payments: {len(payments)}, "
          f"logistics: {len(logistics)}, reviews: {len(reviews)}")

    return users, orders, payments, logistics, reviews


# ------------------------------------------------------------------
# STEP 2: TRANSFORM + LOAD — dim_user
# ------------------------------------------------------------------
def load_dim_user(pg_cursor, users):
    print("LOAD: dim_user ...")
    user_key_map = {}  # user_id -> user_key
    for u in users:
        grp = age_group(u["dob"])
        pg_cursor.execute(
            """INSERT INTO dim_user (user_id, name, gender, age_group, city, state, signup_date)
               VALUES (%s,%s,%s,%s,%s,%s,%s) RETURNING user_key""",
            (u["user_id"], u["name"], u["gender"], grp, u["city"], u["state"], u["signup_date"])
        )
        user_key = pg_cursor.fetchone()[0]
        user_key_map[u["user_id"]] = user_key
    print(f"  -> {len(user_key_map)} rows loaded")
    return user_key_map


# ------------------------------------------------------------------
# STEP 3: TRANSFORM + LOAD — dim_product (deduplicated from orders)
# ------------------------------------------------------------------
def load_dim_product(pg_cursor, orders):
    print("LOAD: dim_product ...")
    product_key_map = {}  # (product_id, product_name, brand) -> product_key
    seen = set()
    for o in orders:
        pkey_tuple = (o["product_id"], o["product_name"], o["brand"])
        if pkey_tuple in seen:
            continue
        seen.add(pkey_tuple)
        pg_cursor.execute(
            """INSERT INTO dim_product (product_id, product_name, category, brand)
               VALUES (%s,%s,%s,%s)
               ON CONFLICT (product_id, product_name, brand) DO NOTHING
               RETURNING product_key""",
            (o["product_id"], o["product_name"], o["category"], o["brand"])
        )
        result = pg_cursor.fetchone()
        if result:
            product_key_map[pkey_tuple] = result[0]

    # fetch any that were skipped due to conflict (shouldn't happen with seen-set, but safe)
    pg_cursor.execute("SELECT product_key, product_id, product_name, brand FROM dim_product")
    for row in pg_cursor.fetchall():
        product_key_map[(row[1], row[2], row[3])] = row[0]

    print(f"  -> {len(product_key_map)} unique products loaded")
    return product_key_map


# ------------------------------------------------------------------
# STEP 4: TRANSFORM + LOAD — dim_date (all unique dates across tables)
# ------------------------------------------------------------------
def load_dim_date(pg_cursor, orders, logistics, reviews):
    print("LOAD: dim_date ...")
    all_dates = set()
    for o in orders:
        if o["order_date"]:
            all_dates.add(o["order_date"])
    for l in logistics:
        if l["dispatch_date"]:
            all_dates.add(l["dispatch_date"])
        if l["delivery_date"]:
            all_dates.add(l["delivery_date"])
    for r in reviews:
        if r["review_date"]:
            all_dates.add(r["review_date"])

    date_key_map = {}
    for d in sorted(all_dates):
        date_key = int(d.strftime("%Y%m%d"))
        pg_cursor.execute(
            """INSERT INTO dim_date (date_key, full_date, day, month, month_name, quarter, year, day_name, is_weekend)
               VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
               ON CONFLICT (date_key) DO NOTHING""",
            (date_key, d, d.day, d.month, d.strftime("%B"),
             (d.month - 1) // 3 + 1, d.year, d.strftime("%A"), d.weekday() >= 5)
        )
        date_key_map[d] = date_key

    print(f"  -> {len(date_key_map)} unique dates loaded")
    return date_key_map


# ------------------------------------------------------------------
# STEP 5: TRANSFORM + LOAD — dim_payment (deduplicated)
# ------------------------------------------------------------------
def load_dim_payment(pg_cursor, payments):
    print("LOAD: dim_payment ...")
    payment_key_map = {}
    seen = set()
    for p in payments:
        coupon = p["coupon_code"] if p["coupon_code"] else ""
        key_tuple = (p["payment_mode"], p["payment_status"], coupon)
        if key_tuple in seen:
            continue
        seen.add(key_tuple)
        pg_cursor.execute(
            """INSERT INTO dim_payment (payment_mode, payment_status, coupon_code)
               VALUES (%s,%s,%s)
               ON CONFLICT (payment_mode, payment_status, coupon_code) DO NOTHING""",
            (p["payment_mode"], p["payment_status"], coupon)
        )

    pg_cursor.execute("SELECT payment_key, payment_mode, payment_status, coupon_code FROM dim_payment")
    for row in pg_cursor.fetchall():
        key_tuple = (row[1], row[2], row[3] if row[3] else "")
        payment_key_map[key_tuple] = row[0]

    print(f"  -> {len(payment_key_map)} unique payment combinations loaded")
    return payment_key_map


# ------------------------------------------------------------------
# STEP 6: TRANSFORM + LOAD — dim_logistic (deduplicated)
# ------------------------------------------------------------------
def load_dim_logistic(pg_cursor, logistics):
    print("LOAD: dim_logistic ...")
    logistic_key_map = {}
    seen = set()
    for l in logistics:
        key_tuple = (l["courier_partner"], l["warehouse_location"], l["delivery_status"])
        if key_tuple in seen:
            continue
        seen.add(key_tuple)
        pg_cursor.execute(
            """INSERT INTO dim_logistic (courier_partner, warehouse_location, delivery_status)
               VALUES (%s,%s,%s)
               ON CONFLICT (courier_partner, warehouse_location, delivery_status) DO NOTHING""",
            (l["courier_partner"], l["warehouse_location"], l["delivery_status"])
        )

    pg_cursor.execute("SELECT logistic_key, courier_partner, warehouse_location, delivery_status FROM dim_logistic")
    for row in pg_cursor.fetchall():
        logistic_key_map[(row[1], row[2], row[3])] = row[0]

    print(f"  -> {len(logistic_key_map)} unique logistic combinations loaded")
    return logistic_key_map


# ------------------------------------------------------------------
# STEP 7: TRANSFORM + LOAD — fact_orders (the big one)
# ------------------------------------------------------------------
def load_fact_orders(pg_cursor, orders, payments, logistics, reviews,
                      user_key_map, product_key_map, date_key_map,
                      payment_key_map, logistic_key_map):
    print("LOAD: fact_orders ...")

    # Build lookup dicts keyed by order_id for fast joining
    payment_by_order = {p["order_id"]: p for p in payments}
    logistic_by_order = {l["order_id"]: l for l in logistics}
    rating_by_order = {r["order_id"]: r["rating"] for r in reviews}

    rows_loaded = 0
    for o in orders:
        order_id = o["order_id"]
        pay = payment_by_order.get(order_id)
        log = logistic_by_order.get(order_id)

        user_key = user_key_map.get(o["user_id"])
        product_key = product_key_map.get((o["product_id"], o["product_name"], o["brand"]))
        date_key = date_key_map.get(o["order_date"])

        payment_key = None
        amount_paid = None
        discount_applied = None
        if pay:
            coupon = pay["coupon_code"] if pay["coupon_code"] else ""
            payment_key = payment_key_map.get((pay["payment_mode"], pay["payment_status"], coupon))
            amount_paid = pay["amount_paid"]
            discount_applied = pay["discount_applied"]

        logistic_key = None
        estimated_days = None
        actual_days = None
        if log:
            logistic_key = logistic_key_map.get(
                (log["courier_partner"], log["warehouse_location"], log["delivery_status"])
            )
            estimated_days = log["estimated_days"]
            if log["dispatch_date"] and log["delivery_date"]:
                actual_days = (log["delivery_date"] - log["dispatch_date"]).days

        rating = rating_by_order.get(order_id)

        pg_cursor.execute(
            """INSERT INTO fact_orders
               (order_id, user_key, product_key, date_key, payment_key, logistic_key,
                order_status, quantity, price, amount_paid, discount_applied,
                estimated_delivery_days, actual_delivery_days, rating)
               VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""",
            (order_id, user_key, product_key, date_key, payment_key, logistic_key,
             o["order_status"], o["quantity"], o["price"], amount_paid, discount_applied,
             estimated_days, actual_days, rating)
        )
        rows_loaded += 1

    print(f"  -> {rows_loaded} fact rows loaded")
    return rows_loaded


# ------------------------------------------------------------------
# MAIN ETL DRIVER
# ------------------------------------------------------------------
def main():
    print("=" * 60)
    print("STARTING ETL PIPELINE: MySQL (OLTP) --> PostgreSQL (OLAP)")
    print("=" * 60)

    my_conn = get_mysql_conn()
    my_cursor = my_conn.cursor(dictionary=True)

    pg_conn = get_postgres_conn()
    pg_cursor = pg_conn.cursor()

    try:
        # EXTRACT
        users, orders, payments, logistics, reviews = extract(my_cursor)

        # Clear existing warehouse data (fresh load every run)
        print("\nClearing existing warehouse data ...")
        pg_cursor.execute("TRUNCATE TABLE fact_orders, dim_user, dim_product, dim_date, dim_payment, dim_logistic RESTART IDENTITY CASCADE;")
        pg_conn.commit()

        # TRANSFORM + LOAD dimensions (order matters - fact table depends on these)
        print("\n--- Loading Dimension Tables ---")
        user_key_map = load_dim_user(pg_cursor, users)
        pg_conn.commit()

        product_key_map = load_dim_product(pg_cursor, orders)
        pg_conn.commit()

        date_key_map = load_dim_date(pg_cursor, orders, logistics, reviews)
        pg_conn.commit()

        payment_key_map = load_dim_payment(pg_cursor, payments)
        pg_conn.commit()

        logistic_key_map = load_dim_logistic(pg_cursor, logistics)
        pg_conn.commit()

        # TRANSFORM + LOAD fact table
        print("\n--- Loading Fact Table ---")
        fact_rows = load_fact_orders(
            pg_cursor, orders, payments, logistics, reviews,
            user_key_map, product_key_map, date_key_map,
            payment_key_map, logistic_key_map
        )
        pg_conn.commit()

        print("\n" + "=" * 60)
        print("ETL PIPELINE COMPLETED SUCCESSFULLY")
        print(f"Total fact rows in warehouse: {fact_rows}")
        print("=" * 60)

    except Exception as e:
        pg_conn.rollback()
        print("ERROR during ETL:", e)
        raise
    finally:
        my_cursor.close()
        my_conn.close()
        pg_cursor.close()
        pg_conn.close()
        print("\nConnections closed.")


if __name__ == "__main__":
    main()
